- Load the Kyphosis dataset from "https://raw.githubusercontent.com/pena-rodrigo/artificial/main/kyphosis.csv"

In [3]:
import numpy as np
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/pena-rodrigo/artificial/main/kyphosis.csv')

- Define

X = df.drop('Kyphosis',axis=1)
y = df['Kyphosis']

then divide the data into training and testing with a 0.3 ratio.

In [4]:
X = df.drop('Kyphosis',axis=1)
y = df['Kyphosis']

In [5]:
from sklearn.model_selection import train_test_split
random_seed = 54
X_train, X_test,y_train,y_test = train_test_split(X,y,test_size = 0.3, random_state = random_seed)

- For this assignment, you need to define a random seed:
random_seed = 54,  and use the option random_state=random_seed in the train_test_split function as well as for
DecisionTreeClassifier, RandomForestClassifier, AdaBoostClassifier. It is not necessary to use it for GaussianNB.

- Implement, train, and test DecisionTreeClassifier, RandomForestClassifier with
n_estimators=200, AdaBoostClassifier with n_estimators=500, and GaussianNB().

In [16]:
from sklearn.metrics import classification_report, confusion_matrix

from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(random_state=random_seed)

from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators = 200, random_state = random_seed)

from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=500,random_state=random_seed)

from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()

In [17]:
dtree.fit(X_train,y_train)
prediction = dtree.predict(X_test)

print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

      absent       0.88      0.79      0.83        19
     present       0.50      0.67      0.57         6

    accuracy                           0.76        25
   macro avg       0.69      0.73      0.70        25
weighted avg       0.79      0.76      0.77        25

[[15  4]
 [ 2  4]]


In [15]:
rfc.fit(X_train,y_train)
prediction = rfc.predict(X_test)

print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

      absent       0.81      0.89      0.85        19
     present       0.50      0.33      0.40         6

    accuracy                           0.76        25
   macro avg       0.65      0.61      0.62        25
weighted avg       0.74      0.76      0.74        25

[[17  2]
 [ 4  2]]


In [11]:
clf.fit(X_train,y_train)
prediction = clf.predict(X_test)

print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

      absent       0.88      0.79      0.83        19
     present       0.50      0.67      0.57         6

    accuracy                           0.76        25
   macro avg       0.69      0.73      0.70        25
weighted avg       0.79      0.76      0.77        25

[[15  4]
 [ 2  4]]


In [13]:
gnb.fit(X_train,y_train)
prediction = gnb.predict(X_test)

print(classification_report(y_test,prediction))
print(confusion_matrix(y_test,prediction))

              precision    recall  f1-score   support

      absent       0.86      0.95      0.90        19
     present       0.75      0.50      0.60         6

    accuracy                           0.84        25
   macro avg       0.80      0.72      0.75        25
weighted avg       0.83      0.84      0.83        25

[[18  1]
 [ 3  3]]
