# Exercise 1: Advanced NumPy Operations

In [ ]:
import numpy as np

a) Create a 5x5 matrix with random integer values from a normal distribution (use NumPy's randn)

In [70]:
arr = np.rint(12 + 6*np.random.randn(5,5)).astype(int)

In [71]:
arr

array([[22, 19, 16, 16, 15],
       [10, 17,  9, 18,  5],
       [22, 11,  9, 22, 11],
       [ 4, 15, 20, 20,  9],
       [ 5, 16, 21,  1,  3]])

In [72]:
from scipy import linalg

b) Find the determinant of the matrix.

In [73]:
linalg.det(arr)

451751.9999999999

Exercise 2: Linear Algebra with NumPy

a) Create a 3x3 matrix A with values [1, 2, 3] in the first row, [4, 5, 6] in the second row, and [7, 8, 9] in the third row.

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

b) Create a vector B with values [10, 11, 12].

In [ ]:
B = [10,11,12]

c) Compute the dot product of A and B.

In [ ]:
np.dot(A,B)

array([ 68, 167, 266])

d) Calculate the eigenvalues and eigenvectors of matrix A.

In [ ]:
EW,EV = linalg.eig(A)

In [ ]:
EW,EV

(array([ 1.61168440e+01+0.j, -1.11684397e+00+0.j, -1.30367773e-15+0.j]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

Exercise 3: Introductory SciPy Operations

a) Import the SciPy library.

In [ ]:
import scipy
from scipy import linalg

b) Use SciPy to solve the system of linear equations:

In [ ]:
x = np.array([[2,1],[4,-3]])
y = np.array([5,2])

In [ ]:
s = linalg.solve(x,y)

In [ ]:
s

array([1.7, 1.6])

Exercise 4: Basic Statistical Analysis with SciPy


In [ ]:
from scipy import stats

a) Generate a random sample of 100 values.

In [ ]:
random_sample = np.random.randn(100)

In [ ]:
random_sample

array([-0.51622995,  0.10075293, -0.22679269,  0.90827671,  1.55733561,
       -0.19381754,  0.72322041,  1.5484051 ,  0.29953896,  0.53998319,
        0.211166  , -0.20013444,  0.14727521,  2.04636537, -1.94049507,
       -0.09793255,  0.6287668 , -1.30892405,  0.36140844,  0.13359196,
       -1.17091963,  0.23506872,  0.7205163 , -0.66381102,  0.00603553,
        1.2982286 ,  1.84195642,  0.39492389,  0.13181372, -0.83267065,
       -0.35029276,  0.29088094, -0.24151056,  0.69118159,  0.14561029,
       -1.5097125 ,  0.03506531,  1.22408586, -0.13016538, -0.76996451,
        0.61649833, -0.204652  , -1.08602832,  1.13128965, -1.55983915,
        0.40135617,  1.95152378, -0.13231098, -0.48641647, -2.13037611,
        1.46957735,  1.99733619,  1.02094816, -1.08365156, -1.69866041,
       -0.53980696,  0.56949288,  1.54238671,  0.94269332,  0.555583  ,
       -0.72095633,  0.81564341,  0.85752242, -1.29675332,  0.06058094,
        0.83387124, -0.29914119,  0.3270193 ,  0.88596516, -1.39

b) Use SciPy to calculate the mean and median

In [ ]:
mean_val = scipy.mean(random_sample)

<ipython-input-51-867921fc4ed2>:1: DeprecationWarning: scipy.mean is deprecated and will be removed in SciPy 2.0.0, use numpy.mean instead
  mean_val = scipy.mean(random_sample)


In [ ]:
mean_val

0.046297640134847606

In [ ]:
median_val = scipy.median(random_sample)

<ipython-input-54-b1661fd83f7e>:1: DeprecationWarning: scipy.median is deprecated and will be removed in SciPy 2.0.0, use numpy.median instead
  median_val = scipy.median(random_sample)


In [ ]:
median_val

0.13270283976659447