Exercise 1: Python Basics


In [ ]:
print('Abigail Shepard')

Abigail Shepard


In [ ]:
num1 = 4
num2 = 841
print(num1+num2)

845


In [ ]:
for i in range(5):
  print(i+1)

1
2
3
4
5


Exercise 2: Data Types

In [ ]:
fruits = ['apple','orange','banana']

In [ ]:
fruits

['apple', 'orange', 'banana']

In [ ]:
months = ('January','February', 'March')

In [ ]:
months

('January', 'February', 'March')

In [ ]:
countries = {'United States': 331900000,'France': 67750000, 'Egypt': 109300000}

In [ ]:
countries

{'United States': 331900000, 'France': 67750000, 'Egypt': 109300000}

Exercise 3: NumPy Basics

In [ ]:
import numpy as np

In [ ]:
array = np.arange(1,6)

In [ ]:
array

array([1, 2, 3, 4, 5])

In [ ]:
np.mean(array)

3.0

In [ ]:
array1 = np.random.randint(1, 11, size=(2, 3))

In [ ]:
array1

array([[ 7,  8, 10],
       [10,  9,  5]])

In [ ]:
array1.reshape(3,2)

array([[ 7,  8],
       [10, 10],
       [ 9,  5]])

Exercise 4: NumPy Array Operations

In [ ]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [ ]:
array1+array2

array([5, 7, 9])

In [ ]:
np.concatenate((array1,array2), axis = None)

array([1, 2, 3, 4, 5, 6])

In [ ]:
array1 * array2

array([ 4, 10, 18])

Exercise 5: NumPy Indexing and Slicing

In [ ]:
oldArray = np.array([10,20,30,40,50])

In [ ]:
oldArray

array([10, 20, 30, 40, 50])

In [ ]:
print(oldArray[3])

40


In [ ]:
newArray = oldArray[1:4]

In [ ]:
newArray

array([20, 30, 40])